#!/usr/bin/env python3.9
import os, sys

from src.connection import Connection
from src.database import Database

import argparse


parser = argparse.ArgumentParser()
parser.add_argument("-m", "--migrate", action="store_true",
                    help="Make migrations")
args = parser.parse_args()

if args.migrate:
    print("Making migrations...")
    Database().migrations()
else:
    print('Starting server...') # u'\u2713'
    Connection()

